import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../../core/utils/validators.dart';
import '../../domain/models/task_model.dart';
import '../providers/task_providers.dart';

class AddTaskScreen extends ConsumerStatefulWidget {
  const AddTaskScreen({super.key});

  @override
  ConsumerState<AddTaskScreen> createState() => _AddTaskScreenState();
}

class _AddTaskScreenState extends ConsumerState<AddTaskScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();

  DateTime _selectedDate = DateTime.now();
  String? _startTime;
  String? _endTime;
  TaskPriority _selectedPriority = TaskPriority.medium;
  String _selectedCategory = 'General';
  final List<String> _categories = ['General', 'Study', 'Coding', 'Health', 'Meeting'];

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _showSnackBar(String message, {bool isError = true}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Icon(
              isError ? Icons.error_outline : Icons.check_circle_outline,
              color: Colors.white,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w500),
              ),
            ),
          ],
        ),
        backgroundColor: isError ? const Color(0xFFEF4444) : const Color(0xFF10B981),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
        elevation: 4,
      ),
    );
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now().add(const Duration(days: 365 * 2)),
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  Future<void> _selectTime(bool isStart) async {
    final now = TimeOfDay.now();
    final picked = await showTimePicker(
      context: context,
      initialTime: isStart
          ? now
          : (_startTime != null
              ? TimeOfDay(
                  hour: int.parse(_startTime!.split(':')[0]),
                  minute: int.parse(_startTime!.split(':')[1]),
                )
              : now),
    );

    if (picked != null) {
      final timeStr = '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}';
      setState(() {
        if (isStart) {
          _startTime = timeStr;
        } else {
          _endTime = timeStr;
        }
      });
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    // Time validation (if end time is set, start time must also be set)
    if (_endTime != null && _startTime == null) {
      _showSnackBar('Please set a start time before setting an end time.');
      return;
    }

    if (_startTime != null && _endTime != null) {
      if (_startTime!.compareTo(_endTime!) > 0) {
        _showSnackBar('Start time cannot be after end time.');
        return;
      }
    }

    final task = TaskModel(
      id: '', // Will be generated by database
      userId: '', // Will be set by repository
      title: _titleController.text.trim(),
      description: _descriptionController.text.trim().isEmpty
          ? null
          : _descriptionController.text.trim(),
      priority: _selectedPriority,
      status: TaskStatus.pending,
      category: _selectedCategory,
      date: _selectedDate,
      startTime: _startTime,
      endTime: _endTime,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    try {
      await ref.read(taskControllerProvider.notifier).createTask(task);
      if (mounted) {
        _showSnackBar('Task created successfully!', isError: false);
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        _showSnackBar(e.toString().replaceAll('Exception: ', ''));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isLoading = ref.watch(taskControllerProvider).isLoading;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Task'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20),
          onPressed: () => context.pop(),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Title Field
                TextFormField(
                  controller: _titleController,
                  textCapitalization: TextCapitalization.sentences,
                  decoration: const InputDecoration(
                    labelText: 'Task Title',
                    hintText: 'What needs to be done?',
                    prefixIcon: Icon(Icons.edit_note_rounded),
                  ),
                  validator: (val) => Validators.validateRequired(val, 'Title'),
                  enabled: !isLoading,
                ),
                const SizedBox(height: 16),

                // Description Field
                TextFormField(
                  controller: _descriptionController,
                  textCapitalization: TextCapitalization.sentences,
                  maxLines: 3,
                  decoration: const InputDecoration(
                    labelText: 'Description (Optional)',
                    hintText: 'Add details here...',
                    prefixIcon: Icon(Icons.description_outlined),
                  ),
                  enabled: !isLoading,
                ),
                const SizedBox(height: 16),

                // Category Field
                DropdownButtonFormField<String>(
                  value: _selectedCategory,
                  decoration: const InputDecoration(
                    labelText: 'Category',
                    prefixIcon: Icon(Icons.category_rounded),
                  ),
                  items: _categories.map((cat) {
                    return DropdownMenuItem(value: cat, child: Text(cat));
                  }).toList(),
                  onChanged: isLoading ? null : (val) {
                    if (val != null) {
                      setState(() {
                        _selectedCategory = val;
                      });
                    }
                  },
                ),
                const SizedBox(height: 20),

                // Date Picker Card
                Card(
                  margin: EdgeInsets.zero,
                  child: ListTile(
                    leading: Icon(Icons.calendar_today_rounded, color: theme.colorScheme.primary),
                    title: const Text('Date'),
                    subtitle: Text(DateFormat('EEEE, MMMM d, yyyy').format(_selectedDate)),
                    trailing: const Icon(Icons.arrow_forward_ios_rounded, size: 16),
                    onTap: isLoading ? null : _selectDate,
                  ),
                ),
                const SizedBox(height: 16),

                // Time Pickers Row
                Row(
                  children: [
                    Expanded(
                      child: Card(
                        margin: EdgeInsets.zero,
                        child: ListTile(
                          contentPadding: const EdgeInsets.symmetric(horizontal: 12),
                          leading: Icon(Icons.access_time_rounded, color: theme.colorScheme.primary),
                          title: const Text('Start'),
                          subtitle: Text(_startTime ?? 'None'),
                          trailing: _startTime != null
                              ? IconButton(
                                  icon: const Icon(Icons.clear, size: 18),
                                  onPressed: () => setState(() => _startTime = null),
                                )
                              : null,
                          onTap: isLoading ? null : () => _selectTime(true),
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Card(
                        margin: EdgeInsets.zero,
                        child: ListTile(
                          contentPadding: const EdgeInsets.symmetric(horizontal: 12),
                          leading: Icon(Icons.access_time_filled_rounded, color: theme.colorScheme.primary),
                          title: const Text('End'),
                          subtitle: Text(_endTime ?? 'None'),
                          trailing: _endTime != null
                              ? IconButton(
                                  icon: const Icon(Icons.clear, size: 18),
                                  onPressed: () => setState(() => _endTime = null),
                                )
                              : null,
                          onTap: isLoading ? null : () => _selectTime(false),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),

                // Priority Selection
                const Text(
                  'Priority',
                  style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                Row(
                  children: TaskPriority.values.map((priority) {
                    final isSelected = _selectedPriority == priority;
                    Color priorityColor;
                    switch (priority) {
                      case TaskPriority.high:
                        priorityColor = const Color(0xFFEF4444);
                        break;
                      case TaskPriority.medium:
                        priorityColor = const Color(0xFFF59E0B);
                        break;
                      case TaskPriority.low:
                        priorityColor = const Color(0xFF3B82F6);
                        break;
                    }

                    return Expanded(
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 4.0),
                        child: ChoiceChip(
                          label: Text(priority.name.toUpperCase()),
                          selected: isSelected,
                          selectedColor: priorityColor.withOpacity(0.15),
                          checkmarkColor: priorityColor,
                          labelStyle: TextStyle(
                            color: isSelected ? priorityColor : theme.colorScheme.onSurface,
                            fontWeight: FontWeight.bold,
                            fontSize: 12,
                          ),
                          onSelected: isLoading
                              ? null
                              : (selected) {
                                  if (selected) {
                                    setState(() {
                                      _selectedPriority = priority;
                                    });
                                  }
                                },
                        ),
                      ),
                    );
                  }).toList(),
                ),
                const SizedBox(height: 36),

                // Save Button
                ElevatedButton(
                  onPressed: isLoading ? null : _submit,
                  child: isLoading
                      ? const SizedBox(
                          height: 24,
                          width: 24,
                          child: CircularProgressIndicator(
                            color: Colors.white,
                            strokeWidth: 2.5,
                          ),
                        )
                      : const Text('Create Task'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
